### PR TITLE
fix RSS link

### PR DESCRIPTION
**Pull request by kokarn**

### CODE REVIEW

**Comment by kokarn** [comment]
It's failing because it's running the command `build` even tho I changed the command to be `ci-build`. I guess I could separate this into two PRs instead if that's a blocker

**Comment by kokarn** [comment]
> CI shouldn't be failing, so please add whatever changes are needed to ensure it passes.

Fair enough. Might do a PR after this then on how to run this on node 20 instead of the legacy stuff currently required :)

**Comment by Nightfirecat** [comment]
The RSS link seems to be working fine for me. What does this change fix?

**Comment by kokarn** [comment]
> The RSS link seems to be working fine for me. What does this change fix?

So basically, because the news thing is infinite scroll, I looked at the source to see if there was RSS, which gives you this 
image

This at least removes the localhost thing from it as that's definitely incorrect. 
Would also help non-js crawlers etc parse it

**Comment by raiyni** [comment]
What news thing? We don't have infinite scrolling anywhere. You should consider looking at the source on https://runelite.net/ not your localhost.

**Comment by kokarn** [comment]
> What news thing? We don't have infinite scrolling anywhere. You should consider looking at the source on https://runelite.net/ not your localhost.

Yeah true, it's not infinite scroll. Was my mistake not having enough patience scrolling.

Also, I _am_ looking at the source on the site
image

**Comment by Nightfirecat** [comment]
It looks like you updated your master branch with a lot of other changes, so this PR isn't in a useful state anymore.

**Comment by kokarn** [comment]
> It looks like you updated your master branch with a lot of other changes, so this PR isn't in a useful state anymore.

I've reverted all the changes I did in my upgrade branch. But do you want me to recreate the PR with just a single commit, is that what you're after here?

**Comment by Nightfirecat** [comment]
I don't care too much what the commit history looks like, just get it back to the state it was in prior to [`81194b6` (#493)](https://github.com/runelite/runelite.net/pull/493/commits/81194b6a858c70a9c32898995328a2efad7b2469) and the rest being pushed

**Comment by kokarn** [comment]
Damn, I was more sloppy than I anticipated. New PR coming

**Pull request closed without merging**
