### PR TITLE
Add full height header adjustments

### PR DESCRIPTION
**Pull request by deathbeam**
- Change current header from being fixed size to resize to full height
of the window
- Change the navbar position to be fixed top
- Change navbar color to dark with transparent background in case it is
on top of header
- Merge github stars button with the customizable buttons row in header

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

Preview:
screenie

### CODE REVIEW

**Comment by Kamielvf** [comment]
Maybe add some kind of icon (like an arrow down) in the bottom center of the header that jumps to the page below?

**Comment by deathbeam** [comment]
Good idea, added locally. Here is what I have rn:

screenie

**Comment by deathbeam** [comment]
Latest version with small adjustments in header:

screenie

**Comment by deathbeam** [comment]
Latest design, both on PC and on simulated mobile screen:

screenie-mobile
screenie

**Comment by deathbeam** [comment]
Added link from Latest release to 'Latest news' section below. Preview:

screenie

**Pull request merged**
