### PR TITLE
Homepage improvements

### PR DESCRIPTION
**Pull request by gc**
This significantly reduces the size (5mb~ -> 1mb~) of the homepage, and makes the initial load smoother.

**Changes**
- Fix the "flash of loading spinner" visual bug, by not awaiting the fetch of the bootstrap.
- Convert the carousel images to webp, to make them significantly smaller.
- Lazyload the blog section on the homepage, so that a large video file doesnt download on every page visit.
- Convert the Runelite logo to webp, and make it smaller. (Its around 1000px, but only shows something like 50x50).
- Move the font-awesome css into the app.css file
- Remove the IE11 polyfill (internet explorer is EOL)
- Set the feature cards to have a low fetchpriority, as they are below the fold, and can impact load time of the visible images.

**Demo** (you might get a warning that it looks like a phishing site because I chose runelite-net as the name)
Before: https://edb92a9a.runelite-net.pages.dev/
After: https://homepage-fix.runelite-net.pages.dev/

Google Lighthouse report
Before: https://pagespeed.web.dev/analysis/https-edb92a9a-runelite-net-pages-dev/zdhmzmwhge?form_factor=mobile
After: https://pagespeed.web.dev/analysis?url=https://homepage-fix.runelite-net.pages.dev/

FYI I'm `@Magnaboy#7556` on discord

### CODE REVIEW

**Comment by Nightfirecat** [comment]
The "Latest commit:" label seems to be missing from the new homepage? Looks pretty nice at a glance

**Comment by gc** [comment]
@Nightfirecat Weird, that worked locally. Should be fixed now in the last commit.

**Review by deathbeam — APPROVED** [review]
Looks good

**Comment by Nightfirecat** [comment]
FWIW I still don't see the latest commit on the homepage anymore. I see it for ~1 frame, then it's hidden again

**Pull request merged**
