### PR TITLE
Add 1.4.10 blog post

### PR DESCRIPTION
**Pull request by deathbeam**
Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

Preview:
screenie

### CODE REVIEW

**Comment by Nightfirecat** [comment]
We should maybe make all the loot tracker images the same width...

Also, minnows image is wrong since Adam made it use a progress pie timer.

**Comment by deathbeam** [comment]
Hmm, can someone send updated screenshot then? And well, it do not looks bad after ran, its next to each other not under each other

**Comment by deathbeam** [comment]
In style of this blog post (for the config panel) https://runelite.net/blog/show/2018-07-05-1.4.6-Release

**Comment by Nightfirecat** [comment]
Adam posted this one, this should probably work: https://cdn.discordapp.com/attachments/419891709883973642/472593430770352137/unknown.png

**Comment by deathbeam** [comment]
Updated the minnows image

**Pull request merged**
